### ISSUE TITLE
Editing an order, then editing another destroys the first edited order

### ISSUE THREAD

**Issue by remotezygote** [doerschera/visual-menu#8]
Screencap:

![editing destroys orders](https://cloud.githubusercontent.com/assets/121182/22228434/01269890-e186-11e6-9e14-b323a404e86c.gif)

**Comment by thomasdoerscher** [comment]
Fixed by above commits: editOrder event handler now calls submitNewOrder action first if data in the new order panel has an order number, then dispatches editOrder action. 

Also fixed issue with changing order numbers when two orders were edited back to back by using action.payload to reference order number instead of previous state order number - 1.
